
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://srozenboim.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Shirley Rozenboim"
title: "Shirley Rozenboim"
description: "Shirley Rozenboim | Software Engineer"
keywords: "rozenboim, engineer, software, full-stack, front-end"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/sanfran.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hello! Welcome to my site!"
  - text: "I am a full-stack software developer currently looking for full-time employment."

me-img: "/img/author.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

############
# Timeline #
############

events:
  - image: "/img/timeline/ucsb.jpg"
    date: "June 2014"
    description: "Graduated from UC Santa Barbara with a B.A. in Economics and Accounting"
  - image: "/img/timeline/oracle.jpg"
    date: "June 2014 - January 2016"
    description: "Worked as an accountant at Oracle, Novogradac & Co, OCHO Candy"
  - image: "/img/timeline/devbootcamp.jpg"
    date: "February 2016 - July 2016"
    description: "Learned to code at Dev Bootcamp"
  - image: "/img/timeline/alexa.png"
    date: "July 2016 - Present"
    description: "Working on various projects including a cyber security startup, Voiceter Pro, and Alexa Babysitter"

# First image of the Timeline

timeline-img: "/img/timeline/code.jpg"
    

###########
# Contact #
###########

email: "srozenboim@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "I am a former accountant turned software engineer. I love to solve problems and create new things!"
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/srozenboim"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/srozenboim"


############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

# keybase-username: johnsmith
# keybase-in-social: True
# keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Projects: 'projects'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
